version: '3.3'
services:
  api:
    image: ghcr.io/shalmeo/shalmeo/xingfu:latest
    stop_signal: SIGINT
    restart: "unless-stopped"
    volumes:
      - .:/usr
    ports:
      - "5000:80"
    depends_on:
      - database
      - redis
    networks:
      - worknet
  database:
    env_file: .env
    image: postgres:14.6-alpine
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: $POSTGRES__LOGIN
      POSTGRES_PASSWORD: $POSTGRES__PASSWORD
      POSTGRES_DB: $POSTGRES__DB
    volumes:
      - "./volumes/postgres/data:/var/lib/postgresql/data"
      - "./volumes/postgres/init:/docker-entrypoint-initdb.d"
    ports:
      - "5432"
    networks:
      - worknet
  redis:
    env_file: .env
    image: redis:7.0-rc-alpine
    container_name: "eiee-redis"
    volumes:
      - "./volumes/redis/redis.conf:/usr/local/etc/redis"
      - "./volumes/redis/data:/data"
    command: "redis-server /usr/local/etc/redis --requirepass ${REDIS__PASSWORD}"
    ports:
      - "6379"
    restart: "unless-stopped"
    networks:
      - worknet

networks:
  worknet:
    driver: bridge